---
# General config.
gitlab_domain: "gitlab-test.wmcloud.org"
gitlab_external_url: "https://{{ gitlab_domain }}/"
gitlab_git_data_dir: "/var/opt/gitlab/git-data"
gitlab_edition: "gitlab-ce"
gitlab_version: "13.11.2-ce.0"
gitlab_config_template: "gitlab.rb.j2"
gitlab_crontab_template: "gitlab-crontab.j2"
gitlab_sshd_template: "gitlab-sshd-config.j2"
gitlab_install_repository: "false"
gitlab_install_dependencies: "false"

# Backups
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_backup_keep_time: "604800"
gitlab_backup_config_keep_num: "6"

gitlab_backup_enable: "true"
gitlab_backup_enable_partial: "true"
gitlab_backup_enable_config: "true"
gitlab_backup_gzip_rsyncable: "yes"
gitlab_backup_max_concurrency: "4"
gitlab_backup_max_storage_concurrency: "1"

# SSL Configuration.
gitlab_redirect_http_to_https: "true"
gitlab_ssl_certificate: "/etc/gitlab/ssl/{{ gitlab_domain }}.crt"
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/{{ gitlab_domain }}.key"

# SSL Self-signed Certificate Configuration.
gitlab_create_self_signed_cert: "true"
gitlab_self_signed_cert_san: "DNS:{{ gitlab_domain }}"
gitlab_self_signed_cert_subj: "/C=US/ST=Missouri/L=Saint Louis/O=IT/CN={{ gitlab_domain }}"
gitlab_self_signed_cert_days: "365"

# LDAP Configuration.
gitlab_ldap_enabled: "false"
gitlab_ldap_host: "example.com"
gitlab_ldap_port: "389"
gitlab_ldap_uid: "sAMAccountName"
gitlab_ldap_method: "plain"
gitlab_ldap_bind_dn: "CN=Username,CN=Users,DC=example,DC=com"
gitlab_ldap_password: "password"
gitlab_ldap_base: "DC=example,DC=com"

# SMTP Configuration
gitlab_smtp_enable: "false"
gitlab_smtp_address: "localhost"
gitlab_smtp_port: "25"
gitlab_smtp_user_name: null
gitlab_smtp_password: null
gitlab_smtp_domain: "localhost"
gitlab_smtp_authentication: "login"
gitlab_smtp_enable_starttls_auto: "true"
gitlab_smtp_tls: "false"
gitlab_smtp_openssl_verify_mode: "none"
gitlab_smtp_ca_path: "/etc/ssl/certs"
gitlab_smtp_ca_file: "/etc/ssl/certs/ca-certificates.crt"

# 2-way SSL Client Authentication support.
gitlab_nginx_ssl_verify_client: ""
gitlab_nginx_ssl_client_certificate: ""

# Probably best to leave this as the default, unless doing testing.
gitlab_restart_handler_failed_when: 'gitlab_restart.rc != 0'

# Dependencies.
gitlab_dependencies:
  - openssh-server
  - curl
  - openssl
  - tzdata
gitlab_dependencies_debian:
  - gnupg

# Optional settings.
gitlab_time_zone: "UTC"
gitlab_download_validate_certs: true
gitlab_default_theme: '2'

# Email configuration.
gitlab_email_enabled: "true"
gitlab_email_from: "gitlab@{{ gitlab_domain }}"
gitlab_email_display_name: "Gitlab"
gitlab_email_reply_to: "gitlab@{{ gitlab_domain }}"

# Registry configuration.
gitlab_registry_enable: "false"
gitlab_registry_external_url: "https://{{ gitlab_domain }}:4567"
gitlab_registry_nginx_ssl_certificate: "/etc/gitlab/ssl/gitlab.crt"
gitlab_registry_nginx_ssl_certificate_key: "/etc/gitlab/ssl/gitlab.key"

# SSH GitLab-specific separate daemon configuration
gitlab_sshd_enable: "true"
gitlab_sshd_listen:
  - 0.0.0.0
gitlab_sshd_port: "2222"
gitlab_sshd_login_grace_time: "60"
gitlab_sshd_host_keys:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
gitlab_sshd_privilege_separation: "sandbox"
gitlab_sshd_kex_algorithms:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256
gitlab_sshd_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512,hmac-sha2-256
  - umac-128@openssh.com
gitlab_sshd_ciphers: 
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr
gitlab_sshd_syslog_facility: "AUTH"
gitlab_sshd_log_level: "VERBOSE"
gitlab_sshd_accept_env: "LANG LC_*"
gitlab_sshd_max_startups: "10:30:60"
gitlab_sshd_max_sessions: 10
gitlab_sshd_max_auth_tries: 3

# CAS integration
gitlab_cas_enable: "true"
gitlab_cas_external: "true"
gitlab_cas_auto_sign_in: "false"
gitlab_cas_auto_create_users: "true"
gitlab_cas_url: "https://idp.wmcloud.org"
gitlab_cas_login_url: "/login"
gitlab_cas_logout_url: "/logout"
gitlab_cas_service_validate_url: "/p3/serviceValidate"
gitlab_cas_name: "cas3"
gitlab_cas_label: "Wikimedia Dev Account"
gitlab_cas_sync_email: "true"
gitlab_cas_sync_profile: "true"
gitlab_cas_sync_attrs: "true"
